name: Update Translations
on:
  workflow_dispatch:  # 수동 실행
  schedule:
    - cron: '0 0 * * *'  # 매일 자정

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Clasp
        run: npm install -g @google/clasp
        
      - name: Authenticate with Google
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
          clasp login --creds credentials.json
          
      - name: Run Translation Script
        run: |
          clasp run updateTranslations
        env:
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
          
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add locales/*.json
          git commit -m "Update translations" || exit 0
          git push
